version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - ENV=DEV
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - 8080:8000
    volumes:
      - ./app:/app
    depends_on:
      - database

  database:
    image: postgres:15-alpine
    volumes:
      - dev-db-data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=dev-user
      - POSTGRES_PASSWORD=changeme

  loadtest:
    build:
      context: .
      dockerfile:  ./Dockerfile
    ports: 
      - 8089:8089
    volumes:
      - ./app:/app

volumes:
  dev-db-data: