---
name: Checks on different system
on:
  pull_request:
    branches:
      - main

jobs:
    Run-on-ubuntu:
        name: Test and Lint Ubuntu
        runs-on: ubuntu-latest
        steps:
            - name: Login docker hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USER }}
                password: ${{ secrets.DOCKER_TOKEN }}
            - name: Checkout
              uses: actions/checkout@v4
            - name: Test
              run: docker-compose run --rm  backend sh  -c "python manage.py wait_for_db && python manage.py test"
            - name: Format
              run: docker-compose run --rm  backend sh  -c "black ." 